[package]
name = "lite_client"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = {version = "1.23.2", features = ["derive"]}
env_logger = "0.11.8"
flume = "0.11.1"
nokhwa = {version = "0.10.9", features = ["output-wgpu"]}
pollster = "0.4.0"
wgpu = "23.0.1"
winit = "0.30.12"
