// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

#![allow(unused, clippy::all)]
use super::camera_type::Camera;
use super::db_vec_3_type::DbVec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `camera`.
///
/// Obtain a handle from the [`CameraTableAccess::camera`] method on [`super::RemoteTables`],
/// like `ctx.db.camera()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.camera().on_insert(...)`.
pub struct CameraTableHandle<'ctx> {
    imp: __sdk::TableHandle<Camera>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `camera`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CameraTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CameraTableHandle`], which mediates access to the table `camera`.
    fn camera(&self) -> CameraTableHandle<'_>;
}

impl CameraTableAccess for super::RemoteTables {
    fn camera(&self) -> CameraTableHandle<'_> {
        CameraTableHandle {
            imp: self.imp.get_table::<Camera>("camera"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CameraInsertCallbackId(__sdk::CallbackId);
pub struct CameraDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CameraTableHandle<'ctx> {
    type Row = Camera;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Camera> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CameraInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CameraInsertCallbackId {
        CameraInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CameraInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CameraDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CameraDeleteCallbackId {
        CameraDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CameraDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Camera>("camera");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct CameraUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CameraTableHandle<'ctx> {
    type UpdateCallbackId = CameraUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CameraUpdateCallbackId {
        CameraUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CameraUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Camera>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Camera>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `camera`,
/// which allows point queries on the field of the same name
/// via the [`CameraIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.camera().identity().find(...)`.
pub struct CameraIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Camera, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CameraTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `camera`.
    pub fn identity(&self) -> CameraIdentityUnique<'ctx> {
        CameraIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CameraIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Camera> {
        self.imp.find(col_val)
    }
}
