// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vec_3_type::DbVec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Camera {
    pub identity: __sdk::Identity,
    pub camera_id: u32,
    pub position: DbVec3,
    pub pitch: f32,
    pub roll: f32,
    pub yaw: f32,
    pub fov: f32,
}

impl __sdk::InModule for Camera {
    type Module = super::RemoteModule;
}
