// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::voxel_grid_type::VoxelGrid;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `voxel_grid`.
///
/// Obtain a handle from the [`VoxelGridTableAccess::voxel_grid`] method on [`super::RemoteTables`],
/// like `ctx.db.voxel_grid()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voxel_grid().on_insert(...)`.
pub struct VoxelGridTableHandle<'ctx> {
    imp: __sdk::TableHandle<VoxelGrid>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `voxel_grid`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VoxelGridTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VoxelGridTableHandle`], which mediates access to the table `voxel_grid`.
    fn voxel_grid(&self) -> VoxelGridTableHandle<'_>;
}

impl VoxelGridTableAccess for super::RemoteTables {
    fn voxel_grid(&self) -> VoxelGridTableHandle<'_> {
        VoxelGridTableHandle {
            imp: self.imp.get_table::<VoxelGrid>("voxel_grid"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VoxelGridInsertCallbackId(__sdk::CallbackId);
pub struct VoxelGridDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VoxelGridTableHandle<'ctx> {
    type Row = VoxelGrid;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VoxelGrid> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VoxelGridInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoxelGridInsertCallbackId {
        VoxelGridInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VoxelGridInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VoxelGridDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoxelGridDeleteCallbackId {
        VoxelGridDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VoxelGridDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VoxelGrid>("voxel_grid");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct VoxelGridUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VoxelGridTableHandle<'ctx> {
    type UpdateCallbackId = VoxelGridUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VoxelGridUpdateCallbackId {
        VoxelGridUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VoxelGridUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<VoxelGrid>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VoxelGrid>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `voxel_grid`,
/// which allows point queries on the field of the same name
/// via the [`VoxelGridIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voxel_grid().id().find(...)`.
pub struct VoxelGridIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VoxelGrid, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VoxelGridTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `voxel_grid`.
    pub fn id(&self) -> VoxelGridIdUnique<'ctx> {
        VoxelGridIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VoxelGridIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<VoxelGrid> {
        self.imp.find(col_val)
    }
}
