// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

#![allow(unused, clippy::all)]
use super::voxel_entry_type::VoxelEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `voxel_entry`.
///
/// Obtain a handle from the [`VoxelEntryTableAccess::voxel_entry`] method on [`super::RemoteTables`],
/// like `ctx.db.voxel_entry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voxel_entry().on_insert(...)`.
pub struct VoxelEntryTableHandle<'ctx> {
    imp: __sdk::TableHandle<VoxelEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `voxel_entry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VoxelEntryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VoxelEntryTableHandle`], which mediates access to the table `voxel_entry`.
    fn voxel_entry(&self) -> VoxelEntryTableHandle<'_>;
}

impl VoxelEntryTableAccess for super::RemoteTables {
    fn voxel_entry(&self) -> VoxelEntryTableHandle<'_> {
        VoxelEntryTableHandle {
            imp: self.imp.get_table::<VoxelEntry>("voxel_entry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VoxelEntryInsertCallbackId(__sdk::CallbackId);
pub struct VoxelEntryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VoxelEntryTableHandle<'ctx> {
    type Row = VoxelEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VoxelEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VoxelEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoxelEntryInsertCallbackId {
        VoxelEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VoxelEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VoxelEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoxelEntryDeleteCallbackId {
        VoxelEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VoxelEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VoxelEntry>("voxel_entry");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct VoxelEntryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VoxelEntryTableHandle<'ctx> {
    type UpdateCallbackId = VoxelEntryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VoxelEntryUpdateCallbackId {
        VoxelEntryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VoxelEntryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<VoxelEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VoxelEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `voxel_entry`,
/// which allows point queries on the field of the same name
/// via the [`VoxelEntryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voxel_entry().id().find(...)`.
pub struct VoxelEntryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VoxelEntry, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VoxelEntryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `voxel_entry`.
    pub fn id(&self) -> VoxelEntryIdUnique<'ctx> {
        VoxelEntryIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VoxelEntryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<VoxelEntry> {
        self.imp.find(col_val)
    }
}
